[package]
name = "husky"
version = "0.1.0"
authors = ["Lester Covey <me@lestercovey.ml>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.17"
crossterm = "0.22"
unicode-width = "0.1.9"
base64 = "0.13.0"